### ISSUE TITLE
Popper position is wrong with transform: scale

### ISSUE THREAD

**Issue by ismail-codar** [atomiks/floating-ui#10]
This issue also exists floating-ui https://github.com/popperjs/popper-core/issues/376

**Comment by atomiks** [comment]
See docs https://www.floating-ui.com/docs/misc#floating

**Comment by ismail-codar** [comment]
By the way I switched to tippyjs...

I have transform-origin but it on the application root.
Like this:
![image](https://user-images.githubusercontent.com/282104/144603123-ab78f068-1a1e-452e-bd4e-2c8be1c5c308.png)

**Comment by atomiks** [comment]
If the tippy is outside of that container (appended to `document.body`) it should work correctly. `appendTo: () => document.body` if you've made it `interactive`. But this repo is not for Tippy so 😅

**Comment by ismail-codar** [comment]
Thansk @atomiks I don't want to take up any more of your time. If I can correctly simulate this problem on a codesanbox exaample I will reopen this.
