### ISSUE TITLE
Finally a headless popover system 💯 

### ISSUE THREAD

**Issue by Cavitt** [atomiks/floating-ui#16]
Perfect project. Been wanting a cross-platform headless system to manage context menus and popups.

Few features to account for from my experience is scrolling with the window (or closing), focus trapping, escape to close, click away close, changing direction based on screen space. (open to the right if not enough space to the left) the order is difficult, base off of OS file managers.

This should pair well with https://github.com/tamagui/tamagui

**Comment by atomiks** [comment]
I've enabled Discussions so cross-platform talk can be started there
