### ISSUE TITLE
svelte bindings?

### ISSUE THREAD

**Issue by KraXen72** [atomiks/floating-ui#21]
anyone wanna make simple svelte components that just call the package and apply the options passed to it as props with inner text being in a <slot> ??

thanks

**Comment by atomiks** [comment]
If you wanna make one we and want to maintain it we can put it under `@floating-ui` officially

**Comment by KraXen72** [comment]
sure but idk how good is it actually gonna be lol since most svelte wrappers for framework-agnostic libraries use fancy stuff like svelte:component etc and i have no idea how to use that. i'll make it once i need to use it in my project and then reopen this issue ig.
