### ISSUE TITLE
middleware and middlewareData is out of sync when middleware get's updated

### ISSUE THREAD

**Issue by joshwooding** [atomiks/floating-ui#27]
Due to the changes in https://github.com/atomiks/floating-ui/pull/9 the update function is not called when middleware changes. Is this intended? If so I guess if middleware changes update will have to be handled by calling `update()` manually?

**Comment by atomiks** [comment]
If `middleware` changes, then the position should be updated as well, so this would be a bug, unless there's no way around it...

**Comment by joshwooding** [comment]
Here's a reproduction btw: https://codesandbox.io/s/solitary-field-796u3?file=/src/App.js

**Comment by atomiks** [comment]
cc: @KubaJastrz

**Comment by KubaJastrz** [comment]
Yeah it's a bug. `middleware` is not present in the `update` dependency array anymore, so it doesn't fire after `middleware` changes.

**Comment by KubaJastrz** [comment]
I guess the only available options here are:
1. Force consumers to use `useMemo` in order to control when the middleware changes. In my mind it's counter-intuitive, since `useMemo` is used primarly for optimization, not for a behavior change.
2. Force consumers to use `update` manually and ignore all changes to `useFloating(options)`. This makes a little more sense, but it's bothersome and easy to forget to run `update`.

Hard problem to tackle without doing some kind of deep comparison of `options` (which is annoying for `middleware` functions).

**Comment by joshwooding** [comment]
Not sure how much of an edge case it is. The most obvious example of changing middleware to me is supporting a tooltip with a toggleable arrow. Since arrow needs an element supplied you have to conditionally add it depending if the arrow is present. Unless we are now saying the arrow middleware should accept null as an element?

**Comment by atomiks** [comment]
@joshwooding in v0.3.0 you can now pass a ref to the arrow `element` https://www.floating-ui.com/docs/react-dom#arrow

**Comment by atomiks** [comment]
I think the main issue is the closure. `fn` accesses the outside options passed in, so you can't do any comparisons that won't result in stale options

**Comment by KubaJastrz** [comment]
> fn accesses the outside options passed in

Do you mean the closure where `fn` is declared, `middlewareData`, or [this whole thing](https://github.com/atomiks/floating-ui/blob/dcfbf08878dddadebe2fad9b92a24b84d3b053ed/packages/core/src/computePosition.ts#L72-L82)?

**Comment by atomiks** [comment]
When one calls a middleware, e.g. `shift()` it creates a new closure every time. So if they change the options from like `shift({padding: 5})` to `shift({padding: 10})`, so if we don't change `fn`, then all of its logic is stale.

**Comment by atomiks** [comment]
In all honesty I think requiring an update is the way to go here if they change the middleware. We just need to add it to the docs. I think it's the better tradeoff than forcing `useMemo` and the user ending up with an infinite loop randomly.

With the arrow ref feature I don't think it's too common that you'll be needing to change the middleware, unless you're setting  any other element-related option like `boundary`, which is another thing that could be wrapped to use a `ref` anyways.

**Comment by KubaJastrz** [comment]
Would it be acceptable to compute position on every render if we somehow solve the infinite loop? No memo on options and no manual updates. 

Because that would be the the closest to ideal ux/dx in my mind.

**Comment by atomiks** [comment]
So something like a `skip` ref internally to skip each second render pass?

**Comment by KubaJastrz** [comment]
I haven't debugged it yet why the loop happens, but maybe.

Building onto the idea of manual updates, we could name `options.middleware` as `options.initialMiddleware` and allow people to pass in the new middleware in the update fn. Something like:

```ts
function update(newMiddleware: Middleware[] | (oldMiddleware: Middleware[]) => void): Promise<void>
```
