### ISSUE TITLE
Arrow middleware breaks if ref is null

### ISSUE THREAD

**Issue by split** [atomiks/floating-ui#30]
PR https://github.com/atomiks/floating-ui/pull/23 added support for using ref for arrow, that is awesome. It only seems to have issue when `element.current` is `null`. Then reference is treated as element and everything breaks.

Maybe logic could be something like:
```ts
      if (isRef(element)) {
        if (element.current != null) {
          return arrowCore({element: element.current, padding}).fn(args);
        }
      } else if (element) {
        return arrowCore({element, padding}).fn(args);
      }

      return {};
```

**Comment by atomiks** [comment]
Hmm the TS type only accepts `undefined` tho?

**Comment by split** [comment]
It's quite late here so going for bed. I could do PR tomorrow if someone has not already done it 😄
