### ISSUE TITLE
popper vs floating-ui?

### ISSUE THREAD

**Issue by jpzwarte** [atomiks/floating-ui#4]
Can you add documentation (probably an FAQ) that explains *why* you created floating-ui? What are the pros/cons between floating-ui vs popper 2?

**Comment by atomiks** [comment]
Good idea! I will add a section :-)

**Comment by atomiks** [comment]
I've now added a "Motivation" section on the docs, which you can read here (once Netlify builds it in a couple min from this comment 😆 )

 https://floating-ui.com/docs/motivation
